"""Skill Synthesis Workshop Engine.

Provides automated extraction, parameterization, validation, and publishing
of reusable skills from session transcripts and execution traces. Adheres to
strict repository authoring standards and security policies.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from alpha.config.runtime_paths import project_root
from alpha.skills.authoring import validate_skill_draft
from alpha.skills.forge.forge import SkillForge
from alpha.skills.proposals import scan_proposal_markdown


@dataclass
class SkillDraft:
    """Represents a candidate skill generated by the workshop."""

    name: str
    description: str
    markdown_content: str
    parameters: list[dict[str, Any]] = field(default_factory=list)
    findings: list[str] = field(default_factory=list)
    is_valid: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "markdown_content": self.markdown_content,
            "parameters": self.parameters,
            "findings": self.findings,
            "is_valid": self.is_valid,
            "metadata": self.metadata,
        }


class SkillWorkshopEngine:
    """Autonomous workshop for transforming problem-solving traces into verified skills."""

    @staticmethod
    def _sanitize_name(raw_name: str) -> str:
        """Ensure skill name is lowercase-hyphenated, <= 64 characters."""
        clean = re.sub(r"[^a-zA-Z0-9\s-]", "", raw_name).strip().lower()
        clean = re.sub(r"[\s_]+", "-", clean).strip("-")
        clean = clean[:64].rstrip("-")
        return clean or "custom-task-skill"

    @staticmethod
    def _sanitize_description(raw_desc: str) -> str:
        """Format description into one professional sentence <= 60 chars ending with a period."""
        clean = " ".join((raw_desc or "").split()).strip()
        if not clean:
            clean = "Executes automated workflow tasks."
        # Strip marketing buzzwords
        for word in ("powerful", "comprehensive", "seamless", "advanced", "robust", "cutting-edge", "revolutionary", "ultimate"):
            clean = re.sub(rf"\b{word}\b", "", clean, flags=re.IGNORECASE)
        clean = " ".join(clean.split()).strip()
        if not clean:
            clean = "Executes automated workflow tasks."
        clean = clean.rstrip(" .")
        if len(clean) > 59:
            clean = clean[:59].rstrip(" .")
        return clean + "."

    @classmethod
    def distill_from_trace(
        cls,
        name: str,
        description: str,
        trace_steps: list[dict[str, Any]],
        *,
        when_to_use: list[str] | None = None,
        prerequisites: list[str] | None = None,
        pitfalls: list[str] | None = None,
        verification_cmd: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> SkillDraft:
        """Extract and structure execution steps into a standardized SKILL.md draft."""
        sanitized_name = cls._sanitize_name(name)
        sanitized_desc = cls._sanitize_description(description)

        # Step parameterization via forge
        template, params = SkillForge.extract_parameters(trace_steps)

        when_list = when_to_use or [f"When needing to automate {sanitized_name.replace('-', ' ')}."]
        prereqs_list = prerequisites or ["Verify standard tool dependencies are available."]
        pitfall_list = pitfalls or ["Check file permissions before execution."]
        verify_command = verification_cmd or "python -m pytest tests/ -q"

        # Construct standard SKILL.md layout adhering to REQUIRED_SECTIONS
        body_lines = [
            f"# {sanitized_name}",
            "",
            f"Automated skill package for {sanitized_name.replace('-', ' ')}.",
            "This procedure coordinates execution steps deterministically.",
            "",
            "## When to Use",
            *[f"- {item}" for item in when_list],
            "",
            "## Prerequisites",
            *[f"- {item}" for item in prereqs_list],
            "",
            "## How to Run",
            f"Run the `{sanitized_name}` workflow via the executive agent.",
            "",
            "## Quick Reference",
            "```bash",
            verify_command,
            "```",
            "",
            "## Procedure",
            template if template else "1. Call execution tool to perform workflow tasks.",
            "",
            "## Pitfalls",
            *[f"- {item}" for item in pitfall_list],
            "",
            "## Verification",
            "Execute the verification command:",
            "```bash",
            verify_command,
            "```",
        ]

        body = "\n".join(body_lines)
        findings = validate_skill_draft(sanitized_name, sanitized_desc, body)

        return SkillDraft(
            name=sanitized_name,
            description=sanitized_desc,
            markdown_content=body,
            parameters=[p.model_dump() if hasattr(p, "model_dump") else p.__dict__ for p in params],
            findings=findings,
            is_valid=len(findings) == 0,
            metadata=metadata or {},
        )

    @classmethod
    def distill_from_thread_events(
        cls,
        name: str,
        description: str,
        events: list[dict[str, Any]],
        verification_cmd: str | None = None,
    ) -> SkillDraft:
        """Convert runtime message events (tool calls, inputs, outputs) into trace steps."""
        trace_steps: list[dict[str, Any]] = []
        for ev in events:
            tool_name = ev.get("tool") or ev.get("name")
            args = ev.get("args") or ev.get("parameters") or {}
            if tool_name:
                cmd = args.get("command") or args.get("CommandLine") or ""
                target = args.get("TargetFile") or args.get("path") or args.get("url") or ""
                action = ev.get("action") or f"Execute {tool_name}"
                trace_steps.append(
                    {
                        "tool": tool_name,
                        "action": action,
                        "target": target,
                        "command": cmd,
                    }
                )

        return cls.distill_from_trace(
            name=name,
            description=description,
            trace_steps=trace_steps,
            verification_cmd=verification_cmd,
        )

    @classmethod
    def publish_skill(
        cls,
        draft: SkillDraft,
        *,
        custom_skills_dir: Path | None = None,
        overwrite: bool = False,
    ) -> Path:
        """Validate, audit, then write SKILL.md to the target custom skills directory.

        Audit-before-activation: the static security scan (same scanner and
        CRITICAL block severity as the proposal queue, see
        ``alpha.skills.proposals.scan_proposal_markdown``) runs on the EXACT
        bytes about to be written, BEFORE any directory or file is created in
        the target (a skill-discovery root). Blocked content raises
        ``StaticScanBlockedError`` and nothing lands on disk, so unreviewed or
        malicious content can never activate. Quality validation
        (``draft.is_valid``) remains the earlier, separate gate.
        """
        if not draft.is_valid:
            raise ValueError(f"Cannot publish invalid skill draft: {'; '.join(draft.findings)}")

        full_content = f"---\nname: {draft.name}\ndescription: {draft.description}\nversion: 0.1.0\n---\n\n{draft.markdown_content}\n"
        scan_proposal_markdown(draft.name, full_content)

        base_dir = custom_skills_dir or (project_root() / "skills" / "custom")
        skill_dir = base_dir / draft.name
        skill_dir.mkdir(parents=True, exist_ok=True)

        target_file = skill_dir / "SKILL.md"
        if target_file.exists() and not overwrite:
            raise FileExistsError(f"Skill '{draft.name}' already exists at {target_file}")

        target_file.write_text(full_content, encoding="utf-8")
        return target_file
