"""Diff the working-tree feature manifest against the one recorded at HEAD.

Scratch tooling from the manifest-audit cycle: `head_manifest.json` beside this
file is `git show HEAD:contracts/feature_manifest.json`, and the working tree
copy is regenerated by `scripts/generate_feature_manifest.py`.

Paths are resolved from `__file__` rather than hardcoded, because the original
MSYS-style `/c/Users/...` literals do not resolve under native Windows Python.
"""

import json
from pathlib import Path

BACKEND = Path(__file__).resolve().parent
ROOT = BACKEND.parent

m = json.load(open(ROOT / "contracts" / "feature_manifest.json", encoding="utf-8"))


def label(x):
    out = {}
    for k in ("tools", "routers", "middlewares", "loops", "engines"):
        v = x.get(k)
        out[k] = len(v) if isinstance(v, list) else v
    return out


print("WORKING counts:", label(m))
print("generated_at:", m.get("generated_at"))
print("version:", m.get("version"))

head = json.load(open(BACKEND / "head_manifest.json", encoding="utf-8"))
print("HEAD counts:", label(head))


def ids(x):
    return set(str(i.get("id")) for i in x.get("routers", []) if isinstance(i, dict))


print("\nROUTERS new:", sorted(ids(m) - ids(head)))
print("LOOPS new:", sorted(set(str(i.get("id")) for i in m.get("loops", [])) - set(str(i.get("id")) for i in head.get("loops", []))))
