import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  apiSidebar: [
    'overview',
    {
      type: 'category',
      label: 'REST API',
      collapsed: false,
      items: [
        'rest/overview',
        'rest/authentication',
        'rest/rate-limiting',
        'rest/errors',
        'rest/versioning',
        'rest/pagination',
        'rest/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [
        'agents/list',
        'agents/get',
        'agents/create',
        'agents/update',
        'agents/delete',
        'agents/health',
        'agents/working',
      ],
    },
    {
      type: 'category',
      label: 'Threads',
      items: [
        'threads/list',
        'threads/get',
        'threads/create',
        'threads/update',
        'threads/delete',
        'threads/branch',
        'threads/regenerate',
        'threads/messages',
        'threads/usage',
        'threads/artifacts',
      ],
    },
    {
      type: 'category',
      label: 'Runs',
      items: [
        'runs/create',
        'runs/stream',
        'runs/wait',
        'runs/get',
        'runs/list',
        'runs/cancel',
        'runs/join',
        'runs/events',
        'runs/messages',
        'runs/workspace-changes',
        'runs/artifacts',
        'runs/token-usage',
      ],
    },
    {
      type: 'category',
      label: 'Messages',
      items: [
        'messages/list',
        'messages/get',
        'messages/history',
        'messages/search',
        'messages/feedback',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        'tools/list',
        'tools/get',
        'tools/execute',
        'tools/schemas',
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      items: [
        'skills/list',
        'skills/get',
        'skills/install',
        'skills/reload',
      ],
    },
    {
      type: 'category',
      label: 'Memory',
      items: [
        'memory/search',
        'memory/add',
        'memory/forget',
        'memory/inspect',
        'memory/summarize',
        'memory/consolidate',
      ],
    },
    {
      type: 'category',
      label: 'Sandbox',
      items: [
        'sandbox/upload',
        'sandbox/download',
        'sandbox/list',
        'sandbox/delete',
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      items: [
        'mcp/config',
        'mcp/servers',
        'mcp/tools',
        'mcp/tasks',
      ],
    },
    {
      type: 'category',
      label: 'Skills',
      items: [
        'skills/list',
        'skills/install',
        'skills/create',
        'skills/update',
        'skills/delete',
      ],
    },
    {
      type: 'category',
      label: 'Groups',
      items: [
        'groups/list',
        'groups/create',
        'groups/get',
        'groups/update',
        'groups/delete',
        'groups/members',
        'groups/activity',
        'groups/claims',
        'groups/goals',
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        'projects/list',
        'projects/get',
        'projects/create',
        'projects/update',
        'projects/delete',
        'projects/crew',
        'projects/inspect',
      ],
    },
    {
      type: 'category',
      label: 'Autonomy',
      items: [
        'apex/status',
        'apex/enable',
        'apex/disable',
        'apex/approve',
        'apex/reject',
        'apex/replan',
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [
        'workflows/list',
        'workflows/create',
        'workflows/get',
        'workflows/execute',
        'workflows/runs',
      ],
    },
    {
      type: 'category',
      label: 'System',
      items: [
        'system/health',
        'system/metrics',
        'system/logs',
        'system/config',
        'system/version',
      ],
    },
  ],
};

export default sidebars;