"""The generated documentation index must be classifiable and current.

`docs/INDEX.md` is generated by `scripts/generate_docs_index.py`, which fails
closed: it refuses to emit an index while any Markdown file under `docs/` has no
classification, because guessing a section from a document's title is exactly
the rot the index exists to prevent.

Fail-closed is only useful if the classification table actually covers the tree.
A tracked `docs/` directory with no `DIRECTORY_SECTIONS` rule and no
`FILE_OVERRIDES` entry therefore does two things at once: the generator exits 2,
and the committed `docs/INDEX.md` silently stops describing the library -- while
still reading as a complete, tidy index of everything, because the missing
documents are simply absent from it.

The `docs-index` job in `.github/workflows/lint-check.yml` runs the same
generator through `scripts/check_docs_index_drift.py`, so this failure is already
gating CI; what was missing was any in-suite coverage of *why* it fails, so these
two assertions pin the cause rather than the symptom:

1. every document in the tree is classifiable (no `ConfigError`), and
2. the committed `docs/INDEX.md` is byte-identical to a fresh render.

Both are computed in-process from the real generator: `scan_documents` only
walks and classifies and `render_index` is pure, so nothing is written, no
subprocess is spawned, and no Git revision is needed.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR_REL = Path("scripts/generate_docs_index.py")
INDEX_REL = Path("docs/INDEX.md")


def _load_generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("alpha_generate_docs_index", REPO_ROOT / GENERATOR_REL)
    assert spec is not None and spec.loader is not None, f"cannot load {GENERATOR_REL.as_posix()}"
    module = importlib.util.module_from_spec(spec)
    # `DocumentSpec` is a @dataclass, and dataclasses resolves annotations through
    # `sys.modules[cls.__module__]`; without this registration the decorator
    # raises `AttributeError: 'NoneType' object has no attribute '__dict__'`.
    # scripts/check_generated_drift.py's own generator shim does the same.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def generator() -> ModuleType:
    return _load_generator()


def test_the_documentation_tree_has_no_unclassified_document(generator: ModuleType) -> None:
    """`scan_documents` raises `ConfigError` naming every unclassified path.

    Asserted by running it: the generator's own error message is the contract,
    so the test reads the paths out of that message rather than reimplementing
    the classifier (which could then drift from the generator in the same change
    that broke it).
    """

    try:
        scan = generator.scan_documents(REPO_ROOT, REPO_ROOT / INDEX_REL)
    except generator.ConfigError as exc:
        pytest.fail(f"unclassified document(s) block docs/INDEX.md regeneration and gate CI: {exc}")

    assert len(scan.documents) > 0


def test_the_committed_documentation_index_matches_a_fresh_render(generator: ModuleType) -> None:
    """`docs/INDEX.md` is exactly what the generator produces right now."""

    scan = generator.scan_documents(REPO_ROOT, REPO_ROOT / INDEX_REL)
    generated = generator.render_index(scan.documents).encode("utf-8")
    committed = (REPO_ROOT / INDEX_REL).read_bytes()

    assert committed == generated, (
        f"{INDEX_REL.as_posix()} is stale: {len(scan.documents)} document(s) are classified now but the committed artifact is not the generator's output. Regenerate with `python {GENERATOR_REL.as_posix()}` rather than editing the artifact."
    )
