"""An upstream failure must reach the client as a payload, not an HTML page.

Every Alpha nginx configuration could answer "502 Bad Gateway" with nginx's own
HTML error body. ``api-client.ts`` can only read a failure from a response whose
body carries the server's ``detail``, so an HTML page reduced to a status line —
the one failure mode a client cannot classify, and the one an operator cannot
act on beyond "something between me and the backend".

These tests pin the coded-failure contract on all three shipped configurations
(``docker/nginx/nginx.conf``, ``docker/nginx/nginx.local.conf`` and the Helm
ConfigMap), because a fix that landed in two of the three would leave the
Helm deployment with the bare 502 it has today.

What is deliberately *not* intercepted, and why that is pinned
-------------------------------------------------------------
**503 is left alone.** A 503 arriving through the proxy is generated by the
*Gateway* — the MCP task cancel's worker-stopped 503, run-admission refusals —
and carries a body the client acts on. nginx never synthesises a 503 for a
proxied request, so intercepting it would only ever delete the server's own
reason and replace it with a proxy message. Only 502 and 504 are statuses nginx
itself produces, and only those are rendered here.

**The frontend and provisioner opt out.** The coded bodies name the *gateway*. A
dead frontend is not a dead gateway, so those locations set
``proxy_intercept_errors off`` and keep their own error page.

**SSE is not rewritten mid-stream.** ``error_page`` replaces the *initial*
response only. A stream that already delivered ``200 text/event-stream`` and then
drops is a socket error rather than an HTTP status, so no delivered frame can be
rewritten; and a stream whose gateway is down now fails with a coded JSON body
instead of an opaque page, which is strictly better for the client's reconnect
ladder.

This is a static check, not a live one: it verifies the configuration is shaped
correctly, because exercising a real proxy failure needs the full compose stack
running with the Gateway stopped (see the acceptance note in
``docs/RELIABILITY_ROADMAP.md`` §3.2).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIGS = {
    "docker": REPO_ROOT / "docker/nginx/nginx.conf",
    "local": REPO_ROOT / "docker/nginx/nginx.local.conf",
    "helm": REPO_ROOT / "deploy/helm/alpha/templates/configmap-nginx.yaml",
}

_LOCATION = re.compile(r"(?m)^(?P<indent>\s*)location\s+(?P<matcher>\S.*?)\s*\{")
_NAMED = re.compile(r"(?m)^\s*(?P<name>@[\w-]+)\s*\{")
_ERROR_PAGE = re.compile(r"error_page\s+(?P<codes>[\d\s=@a-z_]+);")
_RETURN_BODY = re.compile(r"return\s+(?P<status>\d{3})\s+'(?P<body>[^']*)'\s*;")
_CONNECTION = re.compile(r"proxy_set_header\s+Connection\s+(?P<value>.+?);")
_UPSTREAM_BLOCK = re.compile(r"(?m)^\s*upstream\s+(?P<name>[\w-]+)\s*\{")


def _read(path: Path) -> str:
    """Return the nginx source, with Helm template control lines removed.

    A Helm ``{{ ... }}`` line is a Go template action, not an nginx directive;
    keeping it would unbalance the brace scan below.
    """
    text = path.read_text(encoding="utf-8")
    return "\n".join(line for line in text.splitlines() if not re.fullmatch(r"\s*\{\{.*", line))


def _block(source: str, start: int) -> str:
    """Return the brace-balanced block beginning at ``start`` (the opening brace)."""
    depth = 0
    for index in range(start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start : index + 1]
    raise AssertionError("unbalanced nginx block")


def _blocks(source: str) -> dict[str, list[str]]:
    """Map every location and named location matcher to its block bodies."""
    found: dict[str, list[str]] = {}
    for pattern in (_NAMED, _LOCATION):
        for match in pattern.finditer(source):
            name = match.group("name") if "name" in match.groupdict() and match.group("name") else match.group("matcher")
            found.setdefault(name, []).append(_block(source, match.end() - 1))
    return found


@pytest.fixture(params=sorted(CONFIGS))
def config(request):
    return request.param, _read(CONFIGS[request.param])


def test_no_configuration_starts_with_a_byte_order_mark(config):
    """A BOM makes nginx reject its own first directive: `unknown directive`.

    Pinned because a config rewritten by a Windows tool picks one up silently —
    the file still looks correct in every diff.
    """
    name, _ = config
    raw = CONFIGS[name].read_bytes()
    assert not raw.startswith(b"\xef\xbb\xbf"), f"{name} config starts with a UTF-8 BOM; nginx will not parse it"


def test_gateway_failures_are_intercepted_and_routed_to_coded_targets(config):
    name, source = config
    assert "proxy_intercept_errors on;" in source, f"{name}: the gateway's coded bodies need interception on"
    codes = {match.group("codes") for match in _ERROR_PAGE.finditer(source)}
    assert "502 = @gateway_bad_gateway" in codes, f"{name}: a bare 502 is what this replaces; it must be routed"
    assert "504 = @gateway_timeout" in codes, f"{name}: an upstream timeout must be routed too"


def test_503_is_never_intercepted(config):
    """Interception must not swallow the Gateway's own 503 payloads."""
    name, source = config
    for match in _ERROR_PAGE.finditer(source):
        listed = re.findall(r"\d{3}", match.group("codes"))
        assert "503" not in listed, f"{name}: intercepting 503 would delete the server's own reason ({match.group(0)})"


@pytest.mark.parametrize(
    ("target", "status", "code"),
    [("@gateway_bad_gateway", "502", "proxy_upstream_down"), ("@gateway_timeout", "504", "proxy_upstream_timeout")],
)
def test_each_target_returns_json_matching_its_own_status(config, target, status, code):
    """The body must not claim a number other than the one returned."""
    name, source = config
    blocks = _blocks(source)
    assert target in blocks, f"{name}: error_page points at a missing target {target}"
    body = _block_body(blocks[target][0])

    assert "default_type application/json;" in body, f"{name}/{target}: the client cannot parse an HTML error page"
    returned = _RETURN_BODY.search(body)
    assert returned is not None, f"{name}/{target}: no coded body returned"
    assert returned.group("status") == status, f"{name}/{target}: return status must be the intercepted one"
    payload = json.loads(returned.group("body"))
    assert payload["http_status"] == int(status), f"{name}/{target}: body must report the status it returns"
    assert payload["error_code"] == code, f"{name}/{target}: the stable code is what api-client.ts classifies"
    assert isinstance(payload["detail"], str) and payload["detail"], f"{name}/{target}: FastAPI's field name is `detail`"


def _block_body(block: str) -> str:
    return block[1:-1]


def test_the_frontend_and_provisioner_are_not_reported_as_the_gateway(config):
    """Their failures are different components and must keep their own pages."""
    name, source = config
    blocks = _blocks(source)
    assert "proxy_intercept_errors off;" in blocks["/"][0], f"{name}: the frontend location must opt out of interception"
    sandboxes = blocks.get("/api/sandboxes", [])
    for body in sandboxes:
        assert "proxy_intercept_errors off;" in body, f"{name}: a dead provisioner is not a dead gateway"


def test_no_location_declares_the_connection_header_twice(config):
    """Two `proxy_set_header Connection` lines send a duplicated hop-by-hop header.

    This is the failure mode a keepalive edit introduces when it clears
    `Connection` in a location that already had one.
    """
    name, source = config
    for matcher, bodies in _blocks(source).items():
        for body in bodies:
            values = [match.group("value").strip() for match in _CONNECTION.finditer(body)]
            assert len(values) <= 1, f"{name}/{matcher}: {len(values)} Connection headers ({values})"


def test_websocket_locations_still_upgrade(config):
    """Clearing `Connection` for pooling must never touch an upgrade location."""
    name, source = config
    upgrades = {matcher: body for matcher, bodies in _blocks(source).items() for body in bodies if "upgrade" in body and "$http_upgrade" in body}
    assert upgrades, f"{name}: expected at least one upgrade location to check"
    for matcher, body in upgrades.items():
        values = [match.group("value").strip() for match in _CONNECTION.finditer(body)]
        assert values, f"{name}/{matcher}: an upgrade location must forward Connection"
        # `''` and `""` both spell "cleared"; a cleared Connection on an
        # upgrade location breaks the handshake it exists to perform.
        assert all(value.strip("'\"") for value in values), f"{name}/{matcher}: an upgrade location must not clear Connection"


def test_connection_reuse_is_offered_where_the_upstream_is_stable():
    """`keepalive` is only meaningful where the upstream address cannot go stale.

    Two of the three configurations proxy a static upstream and may pool; the
    Docker one resolves its upstream per request so a container restart cannot
    leave it holding a dead IP, and a static `upstream {}` block there would
    refuse to start while the gateway container is absent. That trade is
    deliberate, so it is pinned rather than left to drift.
    """
    docker = _read(CONFIGS["docker"])
    assert "proxy_pass http://$gateway_upstream;" in docker
    assert not _UPSTREAM_BLOCK.search(docker), "a static gateway upstream would resolve at parse time and defeat the resolver"

    for key in ("local", "helm"):
        source = _read(CONFIGS[key])
        gateway_blocks = [_block(source, match.end() - 1) for match in _UPSTREAM_BLOCK.finditer(source) if match.group("name").startswith("gateway")]
        assert gateway_blocks, f"{key}: expected a static gateway upstream"
        assert any("keepalive" in body for body in gateway_blocks), f"{key}: the gateway upstream declares no keepalive"
