"""Deterministic Markdown/JSON rendering for the authority census.

Rendering is intentionally boring: sorted records, sorted gates, sorted
unknowns, an injected revision string, and no wall-clock metadata.  A report
that changes because the clock ticked is impossible to review in a diff.

The report is a specification of findings and remediation notes, never an
authority grant.  Suggested changes are rendered as text for a human to
review; this module has no code-writing or configuration-writing capability.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .models import AuditReport, Reversibility, Verdict


def _report_with_revision(report: AuditReport, revision: str | None) -> AuditReport:
    if revision is None or revision == report.revision:
        return report
    return report.model_copy(update={"revision": str(revision)})


def report_to_dict(report: AuditReport, *, revision: str | None = None) -> dict[str, Any]:
    """Return a JSON-ready report mapping with a deterministic shape."""

    return _report_with_revision(report, revision).to_dict()


def render_json(report: AuditReport, *, revision: str | None = None, indent: int = 2) -> str:
    """Render stable UTF-8 JSON with sorted object keys and a final newline."""

    payload = report_to_dict(report, revision=revision)
    return json.dumps(payload, ensure_ascii=False, indent=indent, sort_keys=True) + "\n"


def _md(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _fmt_bool(value: bool) -> str:
    return "yes" if value else "no"


def render_markdown(report: AuditReport, *, revision: str | None = None) -> str:
    """Render a reviewable Markdown report with every blocking class visible."""

    data = _report_with_revision(report, revision)
    lines: list[str] = [
        "# Authority Model Audit",
        "",
        "Generated by `alpha.safety.authority`; this file is a static census, not a grant of authority.",
        "The auditor never imports application code and never edits a route, guard, or configuration default.",
        "",
        f"- Revision: `{_md(data.revision)}`",
        f"- Source files scanned: `{len(data.scanned_files)}`",
        f"- Capabilities: `{len(data.records)}`",
        f"- Gates: `{len(data.gates)}`",
        f"- Unknowns: `{len(data.unknowns)}`",
        "",
        "## Verdicts",
        "",
        "| Verdict | Count |",
        "| --- | ---: |",
    ]
    for verdict in Verdict:
        lines.append(f"| `{verdict.value}` | {data.verdict_counts.get(verdict.value, 0)} |")

    lines.extend(
        [
            "",
            "## Coverage",
            "",
            f"- Protected destructive capabilities: `{data.coverage.numerator}/{data.coverage.denominator}` ({data.coverage.percentage:.1f}%)",
            f"- Denominator definition: every capability classified as non-`{Reversibility.REVERSIBLE.value}`; unknown capabilities are not treated as safe.",
            f"- Ungated destructive capabilities: `{len(data.ungated_destructive_capabilities)}`",
            f"- Ineffective gates: `{len(data.ineffective_gates)}`",
            f"- Gates protecting nothing: `{len(data.coverage.gates_protecting_nothing)}`",
            "",
            "## Unknowns (blocking)",
            "",
        ]
    )
    if data.unknowns:
        for item in data.unknowns:
            lines.append(f"- `{_md(item.location)}` — **{_md(item.kind)}** (`{_md(item.rule_id)}`): {_md(item.reason)}")
    else:
        lines.append("- None observed by the static census.")
    lines.extend(["", "## Ungated destructive capabilities", ""])
    if data.ungated_destructive_capabilities:
        for capability_id in data.ungated_destructive_capabilities:
            record = next((item for item in data.records if item.capability.id == capability_id), None)
            location = record.capability.source if record is not None else capability_id
            rule = record.capability.classification_rule_id if record is not None else "unknown"
            lines.append(f"- `{_md(location)}` — `{_md(capability_id)}` (rule `{_md(rule)}`) — {_md(record.reason) if record is not None else 'no effective default-deny gate'}")
    else:
        lines.append("- None observed.")
    lines.extend(["", "## Ineffective gates", ""])
    if data.ineffective_gates:
        for gate_id in data.ineffective_gates:
            gate = next((item for item in data.gates if item.id == gate_id), None)
            location = gate.source if gate is not None else gate_id
            reason = gate.ineffective_reason if gate is not None else "no deny path could be identified"
            lines.append(f"- `{_md(location)}` — `{_md(gate_id)}`: {_md(reason)}")
    else:
        lines.append("- None observed.")
    lines.extend(["", "## Gates protecting nothing", ""])
    if data.coverage.gates_protecting_nothing:
        for gate_id in data.coverage.gates_protecting_nothing:
            gate = next((item for item in data.gates if item.id == gate_id), None)
            location = gate.source if gate is not None else gate_id
            lines.append(f"- `{_md(location)}` — `{_md(gate_id)}`")
    else:
        lines.append("- None observed.")

    lines.extend(
        [
            "",
            "## Capability records",
            "",
            "| Capability | Source | Action | Reversibility | Class rule | Gate | Verdict | Verdict rule |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for record in data.records:
        gate = record.gate.id if record.gate is not None else "—"
        lines.append(
            "| "
            + " | ".join(
                (
                    _md(record.capability.id),
                    _md(record.capability.source),
                    _md(record.capability.concrete_action),
                    _md(record.capability.reversibility_class.value),
                    _md(record.capability.classification_rule_id),
                    _md(gate),
                    _md(record.verdict.value),
                    _md(record.verdict_rule_id),
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Gate records",
            "",
            "| Gate | Source | Kind | Posture | Can fail | Protects | Rule |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for gate in data.gates:
        lines.append(
            "| "
            + " | ".join(
                (
                    _md(gate.id),
                    _md(gate.source),
                    _md(gate.kind.value),
                    _md(gate.default_posture.value),
                    _fmt_bool(gate.can_fail),
                    _md(", ".join(gate.protects) if gate.protects else "—"),
                    _md(gate.rule_id),
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Review specifications (not applied by the auditor)",
            "",
            "- A `requires_operator_token` capability needs an owner identity, an explicit token scope, and an auditable confirmation before unattended execution.",
            "- An `unknown` capability remains blocking until a human resolves the named path; it must not be reclassified as `safe_unattended` by omission.",
            "- An ineffective gate needs a test that plants a violating input and observes a denial; a green test suite is not evidence that the check can fail.",
            "- A posture flip from `default_deny` to `default_allow` is a release-blocking change and must be reviewed independently.",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def render(report: AuditReport, *, output_format: str = "json", revision: str | None = None) -> str:
    """Render ``json`` or ``markdown``; unknown formats are a usage error."""

    normalized = output_format.casefold()
    if normalized == "json":
        return render_json(report, revision=revision)
    if normalized in {"markdown", "md"}:
        return render_markdown(report, revision=revision)
    raise ValueError(f"unsupported report format: {output_format}")


def write_report(path: str | Path, report: AuditReport, *, output_format: str = "json", revision: str | None = None) -> Path:
    """Write exactly one declared report path, creating its parent directory."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    text = render(report, output_format=output_format, revision=revision)
    with destination.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return destination


__all__ = [
    "render",
    "render_json",
    "render_markdown",
    "report_to_dict",
    "write_report",
]
