"""The Arena engine: a single-elimination tournament of sub-agents.

Alpha's port of the multi-agent arena pattern. One task, N sub-agents, each
dealt a different strategy card (reasoning mode x workflow x strategy), then a
bracket in which every pair attacks, defends and revises, and a judge scores
both revised solutions on a written rubric until one solution survives.
"""

from alpha.arena.models import (
    ArenaBudget,
    ArenaPhase,
    ArenaPlan,
    ArenaPlanRow,
    ArenaStatus,
    AttackRecord,
    AttackSeverity,
    CardPart,
    CardPartKind,
    DefenseRecord,
    DefenseVerdict,
    StrategyCard,
    VerdictScores,
)
from alpha.arena.cards import DEFAULT_DECK_PATH, deal, deal_cards, load_deck, validate_deck
from alpha.arena.rubric import WEIGHTS, decide, weighted_total
from alpha.arena.bracket import CALLS_PER_MATCH, agent_ids, bracket_sizes, is_done, new_run, next_actions, plan, record_attack, record_defense, record_final, record_solution, record_verdict, run_summary, set_cards, spawn_complete, start_round, start_run
from alpha.arena.rubric import RUBRIC_TEXT
from alpha.arena.prompts import TEMPLATES, card_values, fill, render
from alpha.arena.store import ArenaStore, ArenaStoreError, store_root
from alpha.arena.runner import ArenaAgentRunner, ArenaJob, ArenaJobResult, NO_OUTPUT, ScriptedArenaRunner, SubagentArenaRunner
from alpha.arena.executor import ArenaExecutor, ArenaRunError, DEFAULT_JUDGE_ATTEMPTS
from alpha.arena.service import ArenaConfirmationRequired, ArenaService, REASONING_SCOPE
from alpha.arena.config import ArenaConfig, DEFAULT_ESTIMATE_TOKENS_PER_CALL, arena_config
from alpha.arena.task_contract import (
    AcceptanceCheck,
    Constraint,
    Requirement,
    TaskContract,
    TaskType,
)
from alpha.arena.candidate import (
    CandidateArtifact,
    Contribution,
    CoverageStatus,
    RequirementCoverage,
    best_contributions,
    synthesis_gaps,
)
from alpha.arena.repair import (
    Disposition,
    RepairEntry,
    RepairRound,
    fatal_conceded,
    is_terminal,
    parse_repairs,
    unresolved_attacks,
)
from alpha.arena.task_rubrics import (
    TASK_WEIGHTS,
    HardGate,
    any_gate_tripped,
    apply_gates,
    default_gates,
    pair_order,
    weights_for,
    weighted_total_for,
)
from alpha.arena.evidence import (
    ClaimCheck,
    EvidenceLedger,
    Verdict as ClaimVerdict,
    gate_from_ledger,
)
from alpha.arena.synthesis import (
    MergePlan,
    PatchContribution,
    SynthesisResult,
    plan_merge,
    render_markdown,
    synthesize,
)
from alpha.arena.modes import (
    PROFILES,
    Profile,
    ProfileSpec,
    RouteInputs,
    RunMode,
    describe_modes,
    route,
    spec_for,
)

__all__ = [
    "ArenaBudget",
    "ArenaConfirmationRequired",
    "ArenaConfig",
    "ArenaExecutor",
    "ArenaJob",
    "ArenaJobResult",
    "ArenaPhase",
    "ArenaPlan",
    "ArenaPlanRow",
    "ArenaRunError",
    "ArenaService",
    "ArenaStatus",
    "AttackRecord",
    "AttackSeverity",
    "CALLS_PER_MATCH",
    "CARD_DECK",
    "CardPart",
    "CardPartKind",
    "DEFAULT_DECK_PATH",
    "DEFAULT_ESTIMATE_TOKENS_PER_CALL",
    "DEFAULT_JUDGE_ATTEMPTS",
    "DefenseRecord",
    "DefenseVerdict",
    "NO_OUTPUT",
    "PROFILES",
    "REASONING_SCOPE",
    "RUBRIC_TEXT",
    "RouteInputs",
    "RunMode",
    "ScriptedArenaRunner",
    "StrategyCard",
    "SubagentArenaRunner",
    "TASK_WEIGHTS",
    "TEMPLATES",
    "VerdictScores",
    "WEIGHTS",
    "AcceptanceCheck",
    "CandidateArtifact",
    "ClaimCheck",
    "Constraint",
    "Contribution",
    "CoverageStatus",
    "Disposition",
    "EvidenceLedger",
    "HardGate",
    "MergePlan",
    "PatchContribution",
    "Profile",
    "ProfileSpec",
    "RepairEntry",
    "RepairRound",
    "Requirement",
    "RequirementCoverage",
    "RouteInputs",
    "RunMode",
    "SynthesisResult",
    "TaskContract",
    "TaskType",
    "agent_ids",
    "any_gate_tripped",
    "apply_gates",
    "arena_config",
    "best_contributions",
    "bracket_sizes",
    "card_values",
    "deal",
    "deal_cards",
    "decide",
    "default_gates",
    "describe_modes",
    "fatal_conceded",
    "fill",
    "gate_from_ledger",
    "is_done",
    "is_terminal",
    "load_deck",
    "new_run",
    "next_actions",
    "pair_order",
    "parse_repairs",
    "plan",
    "plan_merge",
    "record_attack",
    "record_defense",
    "record_final",
    "record_solution",
    "record_verdict",
    "render",
    "render_markdown",
    "route",
    "run_summary",
    "set_cards",
    "spawn_complete",
    "spec_for",
    "start_round",
    "start_run",
    "store_root",
    "synthesize",
    "synthesis_gaps",
    "unresolved_attacks",
    "validate_deck",
    "weighted_total",
    "weighted_total_for",
    "weights_for",
    "ArenaAgentRunner",
    "ArenaStore",
    "ArenaStoreError",
]