"""Resize the correct alpha logo for the Electron desktop build.

The Electron build currently uses a wrong geometric icon generated by make-icon.mjs.
This script resizes the correct alpha logo (frontend/src/assets/images/alpha.png)
to 512x512 and writes it to electron/build/icon-512.png, replacing the wrong icon.

Also updates make-icon.mjs to read from the alpha logo source so future regenerations
use the correct logo.
"""
import os
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\PREM KUMAR\Videos\alpha")
ALPHA_LOGO = ROOT / "frontend" / "src" / "assets" / "images" / "alpha.png"
ICON_512 = ROOT / "electron" / "build" / "icon-512.png"
ICON_ICO_SRC = ROOT / "electron" / "dist" / ".icon-ico" / "icon.ico"
MAKE_ICON = ROOT / "electron" / "scripts" / "make-icon.mjs"

def main() -> None:
    if not ALPHA_LOGO.exists():
        print(f"ERROR: alpha logo not found at {ALPHA_LOGO}")
        sys.exit(1)

    # 1. Resize the correct alpha logo to 512x512 using Pillow
    try:
        from PIL import Image
    except ImportError:
        print("ERROR: PIL/Pillow not available. Install with: backend\\.venv\\Scripts\\python.exe -m pip install Pillow")
        sys.exit(1)

    img = Image.open(ALPHA_LOGO).convert("RGBA")
    # Scale to fit 512x512, center on a dark tile (matching Electron splash bg #0b0f14)
    target = 512
    scale = target / max(img.width, img.height)
    new_size = (int(img.width * scale), int(img.height * scale))
    img = img.resize(new_size, Image.LANCZOS)
    canvas = Image.new("RGBA", (target, target), (11, 15, 20, 255))
    offset = ((target - img.width) // 2, (target - img.height) // 2)
    canvas.paste(img, offset, img if img.mode == "RGBA" else None)
    canvas.save(ICON_512, "PNG")
    print(f"OK: resized {ALPHA_LOGO.name} ({img.width}x{img.height}) -> {ICON_512} (512x512)")

    # 2. Update make-icon.mjs to read from the alpha logo source
    make_src = ICON_512
    new_make = f'''#!/usr/bin/env node

/**
 * Generate the Alpha desktop icon (512x512 PNG) from the correct alpha logo.
 *
 * The icon is the actual Alpha logo (frontend/src/assets/images/alpha.png),
 * resized and centered on the app's dark tile color. This replaces the previous
 * wrong geometric "flow orbit" mark that did not represent the product.
 *
 * Run:  node scripts/make-icon.mjs   (needs `npm install --no-save sharp`)
 */

import fs from "node:fs";
import path from "node:path";
import {{ fileURLToPath }} from "node:url";
import sharp from "sharp";

const electronDir = fileURLToPath(new URL("..", import.meta.url));
const alphaLogo = path.join(electronDir, "..", "frontend", "src", "assets", "images", "alpha.png");
const outFile = path.join(electronDir, "build", "icon-512.png");

// Read the correct alpha logo, resize to 512x512, center on dark tile.
const svg = null; // no longer used — we read the real alpha logo below

// Ensure alpha logo exists; fall back to geometric mark only if missing.
let sourceBuffer = null;
if (fs.existsSync(alphaLogo)) {{
    sourceBuffer = fs.readFileSync(alphaLogo);
    console.log("Using correct Alpha logo:", alphaLogo);
}} else {{
    console.log("WARNING: alpha logo not found at", alphaLogo, "- using placeholder");
}}

const target = 512;
let resized;
if (sourceBuffer) {{
    resized = await sharp(sourceBuffer)
        .resize(target, target, {{ fit: "contain", background: "#0b0f14" }})
        .png()
        .toBuffer();
}} else {{
    resized = Buffer.from(
`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <rect x="8" y="8" width="496" height="496" rx="112" fill="#0b0f14"/>
  <rect x="8" y="8" width="496" height="496" rx="112" fill="none" stroke="#30363d" stroke-width="10"/>
  <circle cx="256" cy="256" r="118" fill="none" stroke="#58a6ff" stroke-width="44"/>
  <circle cx="348" cy="164" r="52" fill="#58a6ff"/>
  <circle cx="348" cy="164" r="22" fill="#0b0f14"/>
</svg>`);
}}

fs.mkdirSync(path.dirname(outFile), {{ recursive: true }});
await sharp(resized).png().toFile(outFile);
const meta = await sharp(outFile).metadata();
console.log(`icon written: ${{outFile}} (${{meta.width}}x${{meta.height}})`);
'''
    MAKE_ICON.write_text(new_make, encoding="utf-8")
    print(f"OK: updated {MAKE_ICON} to read from the alpha logo source")

    # 3. Also fix the icon.ico in dist (will be regenerated on next electron-builder run,
    #    but we update the source icon-512.png so the exe gets the right icon on rebuild)
    print("NOTE: electron/dist/.icon-ico/icon.ico and the exe will use the new icon after a rebuild (npm run dist).")
    print("The source icon-512.png is now the correct Alpha logo.")
    print(f"    icon-512.png: {ICON_512} ({ICON_512.stat().st_size / 1024:.1f} KB)")
    print(f"    alpha logo source: {ALPHA_LOGO} ({ALPHA_LOGO.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
