"""Generate an authoritative inventory of Alpha's engine packages from the tree.

Closes the docs-code drift gap: `AGENTS.md` under-describes the ~100 packages
under `alpha/`, so this produces a regenerable inventory (with a preview/core
tier hint) straight from the source. Run it after adding or removing a package.

Usage:
    python scripts/generate_engine_inventory.py [--alpha-root PATH] [--out FILE]
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

#: Files mentioning these are flagged "preview/partial" so real vs. simulated
#: engines are distinguishable at a glance.
_PREVIEW_MARKERS = re.compile(
    r"preview-only|simulated|NotImplementedError|not implemented|not yet implemented",
    re.IGNORECASE,
)

_DEFAULT_ALPHA_ROOT = "backend/packages/harness/alpha"


@dataclass
class PackageInfo:
    """One engine package and its size/preview signals."""

    name: str
    files: int
    lines: int
    preview_hits: int

    @property
    def tier(self) -> str:
        return "preview/partial" if self.preview_hits else "core"


def scan_packages(alpha_root: Path) -> list[PackageInfo]:
    """Return one :class:`PackageInfo` per engine package under *alpha_root*."""
    out: list[PackageInfo] = []
    for d in sorted(p for p in alpha_root.iterdir() if p.is_dir()):
        if d.name.startswith("_") or d.name == "__pycache__":
            continue
        files = [f for f in d.rglob("*.py") if "__pycache__" not in f.parts]
        if not files:
            continue
        lines = 0
        hits = 0
        for f in files:
            try:
                text = f.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            lines += text.count("\n") + 1
            hits += len(_PREVIEW_MARKERS.findall(text))
        out.append(PackageInfo(d.name, len(files), lines, hits))
    return out


def render(pkgs: list[PackageInfo]) -> str:
    """Render the inventory as Markdown."""
    total_files = sum(p.files for p in pkgs)
    total_lines = sum(p.lines for p in pkgs)
    preview = [p for p in pkgs if p.preview_hits]
    lines = [
        "# Alpha Engine Inventory",
        "",
        "> Generated by `scripts/generate_engine_inventory.py` — **do not edit by hand.**",
        "> This is the authoritative list of engine packages under",
        "> `backend/packages/harness/alpha/`; `AGENTS.md` should point here rather than",
        "> hand-maintaining a list that drifts.",
        "",
        f"- **Packages:** {len(pkgs)}",
        f"- **Python files:** {total_files}",
        f"- **Total lines:** {total_lines}",
        f"- **Packages with preview/simulated markers:** {len(preview)}",
        "",
        "Tier `preview/partial` means the package's source mentions a preview-only,",
        "simulated, or unimplemented path — inspect before relying on it as production.",
        "",
        "| Package | Files | Lines | Tier |",
        "|---|---:|---:|---|",
    ]
    for p in sorted(pkgs, key=lambda p: (-p.lines, p.name)):
        lines.append(f"| `alpha/{p.name}` | {p.files} | {p.lines} | {p.tier} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the Alpha engine inventory.")
    parser.add_argument("--alpha-root", default=_DEFAULT_ALPHA_ROOT)
    parser.add_argument("--out", default="ENGINE_INVENTORY.md")
    args = parser.parse_args(argv)

    root = Path(args.alpha_root)
    if not root.is_dir():
        print(f"alpha root not found: {root}")
        return 2
    pkgs = scan_packages(root)
    Path(args.out).write_text(render(pkgs), encoding="utf-8")
    print(f"wrote {args.out}: {len(pkgs)} packages, {sum(p.files for p in pkgs)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
