"""Integration-health endpoint: proof that every wired capability is wired.

Reads ``contracts/feature_manifest.json`` (generated by
``backend/scripts/generate_feature_manifest.py``) and reports, per capability
class, how many entries exist and how many are actually referenced at their
declared wiring point. Also exposes live AutonomySupervisor and event-bus status
so the UI's Integration Health panel shows a single honest picture.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from fastapi import APIRouter
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/ops", tags=["ops-integration"])

# contracts/ lives at the repository root: backend/app/gateway/routers/ -> root is 4 up.
_MANIFEST_PATH = Path(__file__).resolve().parents[4] / "contracts" / "feature_manifest.json"


class ClassCoverage(BaseModel):
    total: int = 0
    wired: int = 0
    intentionally_unwired: int = 0
    excluded: int = 0


class IntegrationHealthResponse(BaseModel):
    manifest_found: bool = Field(..., description="Whether the generated manifest was readable")
    manifest_version: str = ""
    coverage: dict[str, ClassCoverage] = Field(default_factory=dict)
    autonomy: dict[str, Any] = Field(default_factory=dict, description="Live AutonomySupervisor status")
    event_bus: dict[str, Any] = Field(default_factory=dict, description="Live event-bus status")
    capabilities: dict[str, Any] = Field(default_factory=dict, description="Per-capability opt-in status from alpha.capabilities.catalog")
    unwired: list[str] = Field(default_factory=list, description="Manifest ids not referenced at their wiring point")
    generated_at: str = ""


def _load_manifest() -> dict[str, Any]:
    try:
        return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _coverage(entries: list[dict[str, Any]]) -> ClassCoverage:
    covered = ClassCoverage(total=len(entries))
    for entry in entries:
        state = str(entry.get("state", ""))
        if entry.get("excluded"):
            covered.excluded += 1
        elif state == "intentionally_unwired":
            covered.intentionally_unwired += 1
        elif entry.get("wired", False):
            covered.wired += 1
    return covered


@router.get("/integration-health", response_model=IntegrationHealthResponse)
async def integration_health(request: Any = None) -> IntegrationHealthResponse:
    manifest = _load_manifest()
    coverage: dict[str, ClassCoverage] = {}
    unwired: list[str] = []

    if manifest:
        for section in ("tools", "routers", "middlewares", "loops"):
            entries = manifest.get(section) or []
            coverage[section] = _coverage(entries)
            for entry in entries:
                if not entry.get("excluded") and entry.get("state") != "intentionally_unwired" and not entry.get("wired", False):
                    unwired.append(f"{section}:{entry.get('id', '?')}")

    autonomy: dict[str, Any] = {}
    event_bus: dict[str, Any] = {}
    try:  # late imports keep this endpoint usable even before full runtime init
        from app.gateway.autonomy.supervisor import get_autonomy_supervisor

        autonomy = get_autonomy_supervisor().status()
    except Exception:
        logger.debug("Autonomy status unavailable", exc_info=True)
    try:
        from alpha.events.bus import get_event_bus

        event_bus = get_event_bus().status()
    except Exception:
        logger.debug("Event bus status unavailable", exc_info=True)

    capabilities: dict[str, Any] = {}
    try:
        from alpha.capabilities import status as capability_status
        from alpha.config.app_config import get_app_config

        capabilities = capability_status(get_app_config().capabilities)
    except Exception:
        logger.debug("Capability status unavailable", exc_info=True)

    return IntegrationHealthResponse(
        manifest_found=bool(manifest),
        manifest_version=str(manifest.get("version", "")),
        coverage=coverage,
        autonomy=autonomy,
        event_bus=event_bus,
        capabilities=capabilities,
        unwired=unwired,
        generated_at=str(manifest.get("generated_at", "")),
    )
