import { ApiClientError } from "./api-client";

/**
 * Idempotent HTTP admission for thread-scoped run creation.
 *
 * The Gateway accepts an optional `Idempotency-Key` header on
 * `POST /threads/{id}/runs`, `/runs/stream` and `/runs/wait`
 * (`app/gateway/routers/thread_runs.py`): it hashes the caller key
 * with the authenticated owner and the thread id, and a retry that
 * reuses a key whose stored `input`/`assistant_id` matches resolves
 * to the *same* run record instead of admitting a second one. That
 * dedupe is the precondition this module is built on — retrying a
 * run-creating POST without the key is exactly the double-charging
 * side-effect failure `alpha.runtime.side_effects` exists to catch,
 * which is why the transport below is opt-in per call site and never
 * a global retry default.
 *
 * What IS retried, and why it is safe
 * ------------------------------------
 * Only a **transport failure**: the `fetch` itself rejected, so no
 * HTTP response was ever received. The server either never saw the
 * request or its response was lost; either way the retry resolves to
 * the same admission through the key. Every other failure shape is
 * *not* retried:
 *
 * - `http` — the server answered. Even a 5xx is the server's
 *   decision, and a 409 on a reused key is information (the stored
 *   request differed), not a transient condition.
 * - `stopped` — the user aborted; retrying would resurrect a
 *   request the caller cancelled.
 * - `response` / `route` — client-side validation failed before
 *   anything was sent.
 *
 * The ladder is the same **equal jitter** the SSE reconnect ladder
 * uses (`half + random(half)` of `min(cap, base·2ⁿ)`): full jitter
 * is uniform over `[0, ceiling]` and can return ~0, which would
 * re-dial the dependency that just failed to deliver a response with
 * no wait at all. Equal jitter spreads the herd *and* guarantees a
 * real floor.
 */

/** A per-logical-request key. Stable across every retry of that request. */
export function newIdempotencyKey(): string {
  // `crypto.randomUUID` is available in every browser that runs this
  // app and in Node 19+; a fallback is deliberately absent — a
  // hand-rolled counter would be weaker than the platform CSPRNG and
  // silently so.
  return crypto.randomUUID();
}

/** Whether the error means "no HTTP response was ever received". */
export function isTransportFailure(error: unknown): boolean {
  return error instanceof ApiClientError && error.kind === "network";
}

/** The fetch shape `apiFetch` (and the test doubles for it) expose. */
export type IdempotentFetcher = (
  path: string,
  init?: RequestInit,
) => Promise<Response>;

export interface IdempotentRequest {
  path: string;
  init?: RequestInit;
  /**
   * One key per logical request, generated by the caller when the
   * user commits the action. A replay or regenerate is a *new*
   * logical request and gets a fresh key — reusing an old key would
   * resolve to the run it already admitted.
   */
  idempotencyKey: string;
}

export interface IdempotentRetryPolicy {
  /** Total attempts, first included. Default 3. */
  attempts?: number;
  /** Backoff base in ms. Default 250. */
  baseDelayMs?: number;
  /** Backoff ceiling in ms. Default 4000. */
  maxDelayMs?: number;
  /** Optional visible transport state for the retries of this request. */
  onRetry?: (status: {
    attempt: number;
    maxAttempts: number;
    phase: "waiting" | "connecting";
  }) => void;
}

const DEFAULT_ATTEMPTS = 3;
const DEFAULT_BASE_DELAY_MS = 250;
const DEFAULT_MAX_DELAY_MS = 4000;

/** Equal-jitter backoff for attempt `n` (1-based): see the module doc. */
function backoffMs(attempt: number, base: number, cap: number): number {
  const ceiling = Math.min(cap, base * 2 ** Math.max(0, attempt - 1));
  const half = Math.floor(ceiling / 2);
  return half + Math.floor(Math.random() * half);
}

/**
 * Wait `delay` ms, or reject with a local stop as soon as the
 * request's own signal aborts. A user cancel must not sit inside a
 * backoff sleep waiting to throw.
 */
function abortableDelay(
  delay: number,
  signal: AbortSignal | undefined,
): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new ApiClientError("stopped"));
      return;
    }
    if (!signal) {
      setTimeout(resolve, delay);
      return;
    }
    const onAbort = () => {
      clearTimeout(timer);
      signal.removeEventListener("abort", onAbort);
      reject(new ApiClientError("stopped"));
    };
    const timer = setTimeout(() => {
      signal.removeEventListener("abort", onAbort);
      resolve();
    }, delay);
    signal.addEventListener("abort", onAbort, { once: true });
  });
}

/**
 * Send one request under an idempotency key, retrying only transport
 * failures with the *same* key, path, headers and body.
 *
 * The key rides as the `Idempotency-Key` header the Gateway's
 * thread-scoped run routes read; the scoped digest the server derives
 * from it is what makes a retry a resume rather than a duplicate.
 * Returns the first response that was actually received — the caller
 * keeps the existing non-2xx handling (`apiFetch` throws `http`
 * errors itself), so a server answer is never swallowed into a
 * retry.
 */
export async function sendIdempotent(
  fetcher: IdempotentFetcher,
  request: IdempotentRequest,
  policy: IdempotentRetryPolicy = {},
): Promise<Response> {
  const attempts = Math.max(1, Math.floor(policy.attempts ?? DEFAULT_ATTEMPTS));
  const base = Math.max(0, policy.baseDelayMs ?? DEFAULT_BASE_DELAY_MS);
  const cap = Math.max(base, policy.maxDelayMs ?? DEFAULT_MAX_DELAY_MS);

  const init: RequestInit = request.init ? { ...request.init } : {};
  const headers = new Headers(init.headers);
  headers.set("Idempotency-Key", request.idempotencyKey);
  init.headers = headers;

  for (let attempt = 1; ; attempt++) {
    if (attempt > 1)
      policy.onRetry?.({
        attempt: attempt - 1,
        maxAttempts: attempts - 1,
        phase: "connecting",
      });
    try {
      return await fetcher(request.path, init);
    } catch (error) {
      // A received answer (any status), a user abort and a
      // client-side validation failure all propagate untouched: only
      // "nothing was ever received" is retryable, and only while the
      // budget lasts.
      if (!isTransportFailure(error) || attempt >= attempts) throw error;
      policy.onRetry?.({
        attempt,
        maxAttempts: attempts - 1,
        phase: "waiting",
      });
      await abortableDelay(
        backoffMs(attempt, base, cap),
        init.signal ?? undefined,
      );
    }
  }
}
